### PR TITLE
Add extra modes u and z

### PR DESCRIPTION
**Pull request by pulkomandy**
- u is for strings using 16bit chars (widechars/unicode)
- z is for skipping over empty areas (0-filled)

### CODE REVIEW

**Comment by nejohnson** [comment]
Hi Adrien,
I like the "z" skip-if-zero tag, very nice.
I have concerns over the "w" wide char one though.  What is the encoding that is used?  I see in your code that you seem to treat it as byte when emitting it (you use %02X and cast the value to unsigned char).  Is the encoding scheme that this machine uses general purpose or is it specific to this processor?  Is it 16-bit UTF-8 by any chance?  If not then I would think about a layout that makes it clear when you're emitting a 16-bit character code and not an ASCII character code.  For example, suppose you had a string that looked like:
012[16-bit character with code 0x3456]78
This would appear as:
`012\5678`
Perhaps instead emit with something like for lines 970-973:
`printf( isprint(c) ? "%c " : "\\x%04X ", c);`
Note the space after each character.  Try that in your tests and see what you think?

**Comment by pulkomandy** [comment]
Hello, sorry for the delay, got busy with other projects.

In the case I tested with, I was just handling ASCII padded to 16 bits (this is on the u'nSP CPU where there is no 8 bit addressing mode, so strings are sometimes stored this way).

I have now modified the code to close and reopen the string, I think that would be more usual in assemblers than escaping? The escaping was copied from the 's' function without changes.

I think this should work ok for utf16, maybe we want to convert it to utf8? Also, maybe there are endianness problems?

**Comment by pulkomandy** [comment]
As far as I can see, the code already handles endianness. It uses nextw() to get the words from the string, which already swaps them depending on the disassembled architecture endianness. Is there anything more to do? Or maybe I shouldn't be using nextw in this case?

**Comment by nejohnson** [comment]
Sorry, yes nextw() is correct.  Let me re-review and get back to you.  Busy times indeed!

**Comment by nejohnson** [comment]
If I may propose: split this change into two smaller changes, one for "u" and one for "z".  Then each new command is in its own little change.  One long term goal for dasmxx is to be able to generate output suitable for feedback back into an assembler, so will need to think a bit more on how these commands will generate output (or not).

**Comment by pulkomandy** [comment]
Hello,

Sorry for once again a long delay in getting back to this. I have submitted two separate PRs with each of the changes separated. Note that they will conflict with each other, as I gave the same number to each of the command. I can adjust the remaining one when either one is merged.

**Comment by nejohnson** [comment]
Hiya, ok I've added in the z/SKIP change, so over to you to update the second change ready for merging.

**Comment by pulkomandy** [comment]
Updated here: https://github.com/nejohnson/dasmxx/pull/8/files

**Pull request closed without merging**
